#ifndef GIVEN_A3_H
#define GIVEN_A3_H

#include <stdio.h>
#include <string.h>
#include <strings.h>
#include <stdlib.h>
#include <stdbool.h>
#include <time.h>
#include <ctype.h>

#define MAX_LENGTH 25
#define NOTE_LENGTH 4

struct Song
{

    int songId;                      // this is auto-generated by the program
                                     // must be unique for each song in the playList
    char songName[MAX_LENGTH];       // name of the song
    char songNotes[21][NOTE_LENGTH]; // every song in this playlist has 21 notes
    struct Song *nextSong;
};
typedef struct Song A3Song;

/*
add a new song to the start of the given linked list if beginOrEnd is 1; add it to the end of the given LL if beginOrEnd is 2
return True for success and False if it fails for any reason
 */
bool addNewSong(A3Song **headLL, int beginOrEnd)
{
    char newSongName[MAX_LENGTH];
    char notesSong[7][NOTE_LENGTH] = {"do", "re", "mi", "fa", "so", "la", "ti"};

    printf("Song name: ");
    scanf("%s", newSongName);
    printf("\n");

    A3Song *newSong = malloc(sizeof(A3Song)); // dynamic memory allocation

    strncpy(newSong->songName, newSongName, MAX_LENGTH); // copy the song name to the new song

    newSong->songId = strlen(newSong->songName) + (rand() % 1000 + 1); //  generate a random song id

    // generate random notes for the song
    for (int i = 0; i < 21; i++)
    {
        strncpy(newSong->songNotes[i], notesSong[rand() % 7], NOTE_LENGTH);
    }

    newSong->nextSong = NULL; // nextSong pointer become last song in the list

    if (beginOrEnd == 1) // add newSong to the start of LL
    {
        newSong->nextSong = *headLL; // link the new song to the head of the list
        *headLL = newSong;           // update the headLL to point to the new song
        printf("\nSong added at the beginning!\n");
    }
    else if (beginOrEnd == 2) // add newSong to the end of LL
    {
        A3Song *temp = *headLL;

        while (temp->nextSong != NULL)
        {
            temp = temp->nextSong; // set temp to the last song or end of list
        }

        temp->nextSong = newSong; // link the last song to the new song

        printf("\nSong added at the end!\n");
    }
    else
    {
        printf("\nInvalid beginOrEnd value passed!!.\n");

        return false;
    }

    free(newSong); // free the allocated memory

    return true;
}

#endif // GIVEN_A3_H
