#ifndef GIVEN_A3_H
#define GIVEN_A3_H

#include <stdio.h>
#include <string.h>
#include <strings.h>
#include <stdlib.h>
#include <stdbool.h>
#include <time.h>
#include <ctype.h>

#define MAX_LENGTH 25
#define NOTE_LENGTH 4

struct Song
{

    int songId;                      // this is auto-generated by the program
                                     // must be unique for each song in the playList
    char songName[MAX_LENGTH];       // name of the song
    char songNotes[21][NOTE_LENGTH]; // every song in this playlist has 21 notes
    struct Song *nextSong;
};
typedef struct Song A3Song;

/*
Count and return the number of times a given note appears in the song identified by givenSongId;

 Return -1 if song not found;
 */
int countNotesInASong(A3Song *headLL, int givenSongId, char whichNote[4])
{
    int numberNotes = 0;

    A3Song *currentSong = headLL;

    while (currentSong != NULL)
    {
        if (currentSong->songId == givenSongId)
        {
            for (int i = 0; i < 21; i++)
            {
                if (strcmp(whichNote, currentSong->songNotes[i]) == 0)
                {
                    numberNotes++;
                }
            }
            return numberNotes; // song found, return the number of notes
        }

        currentSong = currentSong->nextSong; // continue searching
    }

    free(currentSong); // free allocated memory

    return -1; // song not found
}
#endif // GIVEN_A3_H
