#ifndef GIVEN_A3_H
#define GIVEN_A3_H

#include <stdio.h>
#include <string.h>
#include <strings.h>
#include <stdlib.h>
#include <stdbool.h>
#include <time.h>
#include <ctype.h>

#define MAX_LENGTH 25
#define NOTE_LENGTH 4

struct Song
{

    int songId;                      // this is auto-generated by the program
                                     // must be unique for each song in the playList
    char songName[MAX_LENGTH];       // name of the song
    char songNotes[21][NOTE_LENGTH]; // every song in this playlist has 21 notes
    struct Song *nextSong;
};
typedef struct Song A3Song;

/*
create a play list using data given in the file named "musicalNotes.csv"
 */
int createPlayList(A3Song **headLL, char fileName[MAX_LENGTH])
{
    FILE *fPtr = fopen(fileName, "r");

    if (fPtr == NULL)
    {
        return -1;
    }

    char lines[500]; // buffer to read each line
    int songCount = 0;

    fgets(lines, sizeof(lines), fPtr); // discard the first line of the csv file because the first line contain dummy data

    while (fgets(lines, sizeof(lines), fPtr)) // read data to "lines" aka buffer
    {
        A3Song *newSong = malloc(sizeof(A3Song));

        // Tokenize
        char *token = strtok(lines, ",");
        if (!token)
        {
            free(newSong);
            continue;
        }

        // read the song name
        strncpy(newSong->songName, token, MAX_LENGTH);

        // generate a random song id
        newSong->songId = strlen(newSong->songName) + (rand() % 1000 + 1);

        // read the song notes
        for (int i = 0; i < 21; i++)
        {
            token = strtok(NULL, ",");
            strncpy(newSong->songNotes[i], token, NOTE_LENGTH);
        }

        // link list
        newSong->nextSong = NULL; // nextSong pointer become last song in the list

        if (*headLL == NULL) // add 1st song or the playList is empty
        {
            *headLL = newSong;
        }
        else // add new song - the list is not empty
        {
            A3Song *dummy = *headLL;

            while (dummy->nextSong != NULL) // seek to the last node
            {
                dummy = dummy->nextSong;
            }
            dummy->nextSong = newSong;
        }

        songCount++; // update the count of songs
    }

    fclose(fPtr);
    return songCount;
}

#endif // GIVEN_A3_H