#ifndef GIVEN_A3_H
#define GIVEN_A3_H

#include <stdio.h>
#include <string.h>
#include <strings.h>
#include <stdlib.h>
#include <stdbool.h>
#include <time.h>
#include <ctype.h>

#define MAX_LENGTH 25
#define NOTE_LENGTH 4

struct Song
{

    int songId;                      // this is auto-generated by the program
                                     // must be unique for each song in the playList
    char songName[MAX_LENGTH];       // name of the song
    char songNotes[21][NOTE_LENGTH]; // every song in this playlist has 21 notes
    struct Song *nextSong;
};
typedef struct Song A3Song;

/*
 Remove the song identified by givenSongId;

 Return -1 if song doesn't exist
 */
int deleteASongGivenId(A3Song **headLL, int givenSongId)
{
    A3Song *currentNode = *headLL;
    A3Song *prevNode;

    if (currentNode != NULL && currentNode->songId == givenSongId)
    {
        *headLL = currentNode->nextSong; // Changed head
    }

    while (currentNode != NULL && currentNode->songId != givenSongId)
    {
        prevNode = currentNode;
        currentNode = currentNode->nextSong;
    }

    prevNode->nextSong = currentNode->nextSong;

    // givenSongId does not exist
    if (currentNode == NULL)
    {
        return -1;
    }

    // Free memory
    free(currentNode);
    free(prevNode);

    return 1;
}

#endif // GIVEN_A3_H
