#ifndef GIVEN_A3_H
#define GIVEN_A3_H

#include <stdio.h>
#include <string.h>
#include <strings.h>
#include <stdlib.h>
#include <stdbool.h>
#include <time.h>
#include <ctype.h>

#define MAX_LENGTH 25
#define NOTE_LENGTH 4

struct Song
{

    int songId;                      // this is auto-generated by the program
                                     // must be unique for each song in the playList
    char songName[MAX_LENGTH];       // name of the song
    char songNotes[21][NOTE_LENGTH]; // every song in this playlist has 21 notes
    struct Song *nextSong;
};
typedef struct Song A3Song;

/*
 Remove every song from the playlist
 */
void deletePlayList(A3Song **headLL)
{
    A3Song *currentNode = *headLL;
    A3Song *deleteNode;

    while (currentNode != NULL)
    {
        deleteNode = currentNode;
        currentNode = currentNode->nextSong;
        free(deleteNode);
    }

    *headLL = NULL;
}

#endif // GIVEN_A3_H
