#ifndef GIVEN_A3_H
#define GIVEN_A3_H

#include <stdio.h>
#include <string.h>
#include <strings.h>
#include <stdlib.h>
#include <stdbool.h>
#include <time.h>
#include <ctype.h>

#define MAX_LENGTH 25
#define NOTE_LENGTH 4

struct Song
{

    int songId;                      // this is auto-generated by the program
                                     // must be unique for each song in the playList
    char songName[MAX_LENGTH];       // name of the song
    char songNotes[21][NOTE_LENGTH]; // every song in this playlist has 21 notes
    struct Song *nextSong;
};
typedef struct Song A3Song;

// function prototypes
int createPlayList(A3Song **headLL, char fileName[MAX_LENGTH]);
bool addNewSong(A3Song **headLL, int beginOrEnd);
void playPlayList(A3Song *headLL);
int playSongGivenId(A3Song *headLL, int givenSongId);
int playSongGivenName(A3Song *headLL, char givenSongName[MAX_LENGTH]);
int countNotesInASong(A3Song *headLL, int givenSongId, char whichNote[4]);
int deleteASongGivenId(A3Song **headLL, int givenSongId);
void deletePlayList(A3Song **headLL);

int main()
{
    // Declare variables
    A3Song *headLL = NULL;
    int userChoice;
    int numberSongs;                                                             // case 1
    int beginOrEnd;                                                              // case 2
    int givenSongId;                                                             // case 4, 6, 7
    int resultCase4;                                                             // case 4
    char givenSongName[MAX_LENGTH];                                              // case 5
    int resultCase5;                                                             // case 5
    char whichNote[NOTE_LENGTH];                                                 // case 6
    int numberNotes;                                                             // case 6
    char notesSong[7][NOTE_LENGTH] = {"do", "re", "mi", "fa", "so", "la", "ti"}; // case 6
    int resultCase7;                                                             // case 7

    do
    {
        printf("======================================================\n");
        printf("1. Create a new playlist\n");
        printf("2. Add a song to an existing playlist\n");
        printf("3. Play all songs in the given playlist\n");
        printf("4. Play a song from the playlist, given its id\n");
        printf("5. Play a song from the playlist, given its name\n");
        printf("6. Count the number of occurrences of a note in a given song\n");
        printf("7. Delete a song from the playlist, given its id\n");
        printf("8. Delete the entire playlist\n");
        printf("9. Exit\n");
        printf("======================================================\n");

        printf("Enter your choice: ");
        scanf("%d", &userChoice);

        switch (userChoice)
        {
        case 1:
            // createPlayList
            numberSongs = createPlayList(&headLL, "MusicalTunes.csv");

            printf("Number of songs in the playlist: %d\n", numberSongs);

            break;

        case 2:
            // addNewSong
            printf("Enter the value for beginOrEnd: ");
            scanf("%d", &beginOrEnd);

            addNewSong(&headLL, beginOrEnd);

            break;

        case 3:
            // playPlayList
            playPlayList(headLL);

            break;

        case 4:
            // playSongGivenId
            printf("Enter the id of the song you want to play: ");
            scanf("%d", &givenSongId);

            resultCase4 = playSongGivenId(headLL, givenSongId);

            if (resultCase4 == -1)
            {
                printf("\nNo song found!!\n");
            }

            break;

        case 5:
            // playSongGivenName
            printf("Enter the name of the song you want to play: ");
            getchar();
            fgets(givenSongName, MAX_LENGTH, stdin);            // this include "\n" at the last char
            givenSongName[strcspn(givenSongName, "\n")] = '\0'; // seek to the position of "\n" and replace it with '\0' (https://www.w3schools.com/c/ref_string_strcspn.php)

            resultCase5 = playSongGivenName(headLL, givenSongName);

            if (resultCase5 == -1)
            {
                printf("\nNo song found!!\n");
            }

            break;

        case 6:
            // countNotesInASong
            printf("Enter the id of the song you want to count the notes in: ");
            scanf("%d", &givenSongId);
            printf("Enter the note you want to count: ");
            scanf("%s", whichNote);

            numberNotes = countNotesInASong(headLL, givenSongId, whichNote);

            if ((numberNotes == -1) ||
                ((strcmp(whichNote, notesSong[0]) != 0) &&
                 (strcmp(whichNote, notesSong[1]) != 0) &&
                 (strcmp(whichNote, notesSong[2]) != 0) &&
                 (strcmp(whichNote, notesSong[3]) != 0) &&
                 (strcmp(whichNote, notesSong[4]) != 0) &&
                 (strcmp(whichNote, notesSong[5]) != 0) &&
                 (strcmp(whichNote, notesSong[6]) != 0)))
            {
                printf("\nSong not found!!\n");
            }
            else
            {
                printf("\nNumber of times the note appears: %d\n", numberNotes);
            }

            break;

        case 7:
            // deleteASongGivenId
            printf("Enter the id of the song you want to delete: ");
            scanf("%d", &givenSongId);
            printf("\n");

            resultCase7 = deleteASongGivenId(&headLL, givenSongId);

            if (resultCase7 == -1)
            {
                printf("Song not found!!\n");
            }
            else
            {
                printf("Song Deleted!!\n");
            }

            break;

        case 8:
            // deletePlayList
            deletePlayList(&headLL);

            printf("\nDeleting Playlist ♫♫♫\n");

            break;

        case 9:
            // exit program
            printf("\n♫ Exiting the program ♫\n");

            break;
        }
    } while (userChoice != 9);

    return 0;
}

#endif // GIVEN_A3_H

/*
CC= gcc
CFLAGS = -Wall -std=c99 -w


bin/test: TestCode.o unity.o TestCodeRunner.o harness/unity.h harness/CodeUnderTest.h
    $(CC)  $(CFLAGS) -o bin/test TestCode.o unity.o TestCodeRunner.o -lm

TestCode.o: harness/TestCode.c unity.o harness/unity.h
    $(CC)  $(CFLAGS) -c harness/TestCode.c

unity.o: harness/unity.c harness/unity.h
    $(CC)  $(CFLAGS) -c harness/unity.c

TestCodeRunner.o: harness/TestCodeRunner.c harness/unity.h
    $(CC)  $(CFLAGS) -c harness/TestCodeRunner.c

clean test:
    rm *.o bin/test
*/
