#ifndef GIVEN_A3_H
#define GIVEN_A3_H

#include <stdio.h>
#include <string.h>
#include <strings.h>
#include <stdlib.h>
#include <stdbool.h>
#include <time.h>
#include <ctype.h>

#define MAX_LENGTH 25
#define NOTE_LENGTH 4

struct Song
{

    int songId;                      // this is auto-generated by the program
                                     // must be unique for each song in the playList
    char songName[MAX_LENGTH];       // name of the song
    char songNotes[21][NOTE_LENGTH]; // every song in this playlist has 21 notes
    struct Song *nextSong;
};
typedef struct Song A3Song;

/*
Play a song, given its name givenSongName;
each note in the song must be separated by a dot (.)
for example, Do.Re.Mi. and so on

Return -1 if song not found; 1 if found
 */
int playSongGivenName(A3Song *headLL,
                      char givenSongName[MAX_LENGTH])
{
    A3Song *currentSong = headLL;

    while (currentSong != NULL)
    {
        if (strcasecmp(currentSong->songName, givenSongName) == 0)
        // https://www.ibm.com/docs/en/i/7.3?topic=functions-strcasecmp-compare-strings-without-case-sensitivity
        {
            printf("Playing song: %s\n", currentSong->songName);
            for (int i = 0; i < 21; i++)
            {
                printf("%s.", currentSong->songNotes[i]);
            }
            printf("\n");
            return 1; // song found
        }

        currentSong = currentSong->nextSong; // continue searching
    }

    free(currentSong);

    return -1; // song not found
}

#endif // GIVEN_A3_H
