#ifndef GIVEN_A3_H
#define GIVEN_A3_H

#include <stdio.h>
#include <string.h>
#include <strings.h>
#include <stdlib.h>
#include <stdbool.h>
#include <time.h>
#include <ctype.h>

#define MAX_LENGTH 25
#define NOTE_LENGTH 4

struct Song
{

    int songId;                      // this is auto-generated by the program
                                     // must be unique for each song in the playList
    char songName[MAX_LENGTH];       // name of the song
    char songNotes[21][NOTE_LENGTH]; // every song in this playlist has 21 notes
    struct Song *nextSong;
};
typedef struct Song A3Song;

/*
Play all songs in the playlist,
each song separated by a newline;
each note in a song separated by a .
for example, Do.Re.Mi. and so on
 */
void playPlayList(A3Song *headLL)
{
    A3Song *currentSong = headLL;

    while (currentSong != NULL)
    {
        printf("\nSong ID: %d\n", currentSong->songId);
        printf("Song Name: %s\n", currentSong->songName);
        printf("Song Notes:\n");

        for (int i = 0; i < 21; i++)
        {
            printf("%s", currentSong->songNotes[i]);
            if (i < 20)
            {
                printf(".");
            }
        }
        printf("\n");

        currentSong = currentSong->nextSong;
    }

    free(currentSong);
}

#endif // GIVEN_A3_H
